### ISSUE TITLE
"Plugin ID mismatch" error trying to install from within Obsidian

### ISSUE THREAD

**Issue by darthmachina** [phibr0/obsidian-plugin-changelogs#1]
Clicking on "Install" for the plugin from within Obsidian results in an error message "Plugin ID mismatch". I am on the insiders build of Obsidian: 0.12.11.

**Comment by phibr0** [comment]
Oops! I messed up my Plugins (I was fixing stuff in two plugins at the same time, and uploaded the wrong manifest by accident)

Its fixed now!
