### ISSUE TITLE
The plugin doesn't appear to do anything

### ISSUE THREAD

**Issue by swehba** [phibr0/obsidian-plugin-changelogs#2]
Love the idea behind your plugin, but I can seem to get it to work. In your demo video you should several icons next to the enable/disable button for the plugins, but my version of Obsidian does not show any of these buttons. See https://d.pr/i/xZHgmd+. What am I missing?

**Comment by phibr0** [comment]
What Obsidian Version are you using?

**Comment by BricoleurSoul** [comment]
Same problem for me - Obsidian version 21.11.

**Comment by BricoleurSoul** [comment]
So you mention  in the forum - but not here  - that it needs the latest advance build?
And it still doesn't work with that build!
Poor show! 
Sorry but trust level just dropped so I'm Off to uninstall.

**Comment by phibr0** [comment]
For now you will also need install the Hotkey Helper Plugin for this to work. You can find it by searching for "Hotkey Helper" in the Plugin Browser.

**Comment by iris2jane** [comment]
It seems that the changelogs' buttom is still missing
![image](https://user-images.githubusercontent.com/36763930/126997489-f84f4a25-10c5-4a02-91b2-fc5b446801a8.png)

**Comment by phibr0** [comment]
Did you enable both Plugins? Are you also on Obsidian Version 0.12.11? 
In my testing it wasn't required, but maybe a quick restart of Obsidian helps

**Comment by iris2jane** [comment]
> Did you enable both Plugins? Are you also on Obsidian Version 0.12.11?
> In my testing it wasn't required, but maybe a quick restart of Obsidian helps

Yes and Yes
It's weird 🧐

**Comment by phibr0** [comment]
Hm. Could you try it without other Plugins? Like here in a newly created Help Vault:
![PluginChangelogsHelp](https://user-images.githubusercontent.com/59741989/127021501-ce7de674-2574-458f-ada0-129d2ce0aea8.gif)

And please check the Console for Errors

**Comment by iris2jane** [comment]
> Hm. Could you try it without other Plugins? Like here in a newly created Help Vault:
> ![PluginChangelogsHelp](https://user-images.githubusercontent.com/59741989/127021501-ce7de674-2574-458f-ada0-129d2ce0aea8.gif)
> 
> And please check the Console for Errors

It's now nomal after I disable all core and community plugins. And still normal when I  restart all those plugins.

**Comment by iris2jane** [comment]
I got it!
You must install Hotkey first, then install Changelogs. The order of installing is the key😂

**Comment by phibr0** [comment]
That shouldn't matter actually. In the gif i send I also activate the Changelog Plugin first and then the Hotkey Helper

**Comment by connoryang331** [comment]
Sorry. I disabled all community plugins, and then open hot helper and changlog plugins,  it doesn't appear anything.
