### ISSUE TITLE
Feature Request: Exclude core  plugins

### ISSUE THREAD

**Issue by brimwats1** [phibr0/obsidian-plugin-changelogs#4]
Core  plugins also register changelogs, but clicking on them gives "something went wrong" 

![image](https://user-images.githubusercontent.com/49103046/133344005-322d545e-ebc5-4632-9966-c66ccc962d9a.png)

![image](https://user-images.githubusercontent.com/49103046/133344006-aba3db98-a9e8-4e3d-bfc9-2452b4738a7f.png)

**Comment by phibr0** [comment]
Should be fixed in the next Release
